#!/usr/bin/env python3
"""Push section 4 of the canonical skill out to the copies that mirror it.

The doctrine lives in several places and drifts: the two entries generated by a
stale claude.ai copy were the worst on the site. One command keeps them equal.

  python3 tools/sync_doctrine.py
"""
import os
import subprocess
import sys

CANON = ".claude/skills/pearls/SKILL.md"
MIRROR = "claude-ai-skill/pearls/reference/design-system.md"
ZIP_DIR, ZIP_NAME = "claude-ai-skill", "pearls-skill.zip"

HEADER = """# Pearl design system — the White Book register

<!-- MIRROR: this file is section 4 of .claude/skills/pearls/SKILL.md, verbatim.
     That file is canonical. Edit section 4 there, then re-run
     tools/sync_doctrine.py, which rewrites this file and the zip. -->

"""


def main():
    if not os.path.exists(CANON):
        print("run from the repo root", file=sys.stderr)
        return 2
    t = open(CANON, encoding="utf-8").read()
    sec4 = t[t.index("## 4 · Design the entry"):t.index("## 5 · Manifest")].rstrip() + "\n"

    want = HEADER + sec4
    if open(MIRROR, encoding="utf-8").read() != want:
        open(MIRROR, "w", encoding="utf-8").write(want)
        print(f"updated {MIRROR}")
    else:
        print(f"{MIRROR} already current")

    zp = os.path.join(ZIP_DIR, ZIP_NAME)
    if os.path.exists(zp):
        os.remove(zp)
    subprocess.run(["zip", "-q", "-r", ZIP_NAME, "pearls"], cwd=ZIP_DIR, check=True)
    print(f"rebuilt {zp} ({os.path.getsize(zp)} bytes)")
    print("\nRe-zipping alone changes nothing on the account — upload it at "
          "claude.ai → Settings → Capabilities → Skills → pearls → (open it) → ⋮ → Replace.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
