#!/usr/bin/env python3
"""Push section 4 of the canonical skill out to every copy that mirrors it.

The doctrine lives in six places and was already drifting: the two entries
generated by a stale claude.ai copy were the worst on the site. One command
rewrites the mirrors, so "I edited the canonical file" is the whole workflow.

  python3 tools/sync_doctrine.py
"""
import os
import re
import subprocess
import sys

CANON = ".claude/skills/pearls/SKILL.md"
MIRROR = "claude-ai-skill/pearls/reference/design-system.md"
ZIP_DIR, ZIP_NAME = "claude-ai-skill", "pearls-skill.zip"

HEADER = """# Pearl design system — entry authoring doctrine

<!-- MIRROR: this file is section 4 of .claude/skills/pearls/SKILL.md, verbatim.
     That file is canonical. Do not edit this copy by hand — edit section 4 there
     and re-run tools/sync_doctrine.py, which rewrites this file and the zip.
     tools/check_doctrine_drift.py fails CI if they diverge. -->

"""


def section4(text):
    i = text.index("## 4 · Design the entry")
    j = text.index("## 5 · Manifest")
    return text[i:j].rstrip() + "\n"


def main():
    if not os.path.exists(CANON):
        print("run from the repo root", file=sys.stderr)
        return 2
    sec4 = section4(open(CANON, encoding="utf-8").read())

    want = HEADER + sec4
    had = open(MIRROR, encoding="utf-8").read() if os.path.exists(MIRROR) else ""
    if had != want:
        open(MIRROR, "w", encoding="utf-8").write(want)
        print(f"updated {MIRROR}")
    else:
        print(f"{MIRROR} already current")

    zp = os.path.join(ZIP_DIR, ZIP_NAME)
    if os.path.exists(zp):
        os.remove(zp)
    subprocess.run(["zip", "-q", "-r", ZIP_NAME, "pearls"], cwd=ZIP_DIR, check=True)
    print(f"rebuilt {zp} ({os.path.getsize(zp)} bytes)")
    print("\nRe-zipping alone changes nothing on the account — upload it at "
          "claude.ai → Settings → Capabilities → Skills → pearls → ⋮ → Replace.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
